#!/command/with-contenv sh
if [ "${DISABLE_MACHINE_LEARNING}" = "true" ]; then
    echo "[immich-ml] Machine learning disabled, sleeping."
    exec s6-sleep infinity
fi

cd /opt/immich-ml
export PYTHONPATH="/opt/immich-ml"
export PATH="/opt/venv/bin:$PATH"
export MACHINE_LEARNING_CACHE_FOLDER="/data/model-cache"
export IMMICH_HOST="127.0.0.1"
export IMMICH_PORT="${ML_PORT:-3003}"

exec python -m immich_ml
