#!/command/with-contenv sh
mkdir -p /data/redis
chown -R redis:redis /data/redis

exec s6-setuidgid redis redis-server \
    --dir /data/redis \
    --bind 127.0.0.1 \
    --port 6379 \
    --maxmemory 256mb \
    --maxmemory-policy noeviction \
    --save 60 1000 \
    --save 300 100
